# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'bugCrush' do
    pod 'SwiftSpinner', '~> 0.8.0'
end

target 'bugCrushTests' do

end

target 'bugCrushUITests' do

end

